feature { name: "ackdat" type: FLOAT }
feature { name: "ct_flw_http_mthd" type: INT }
feature { name: "ct_ftp_cmd" type: INT }
feature { name: "ct_src_dport_ltm" type: INT }
feature { name: "ct_dst_sport_ltm" type: INT }
feature { name: "dbytes" type: INT }
feature { name: "dinpkt" type: FLOAT }
feature { name: "djit" type: FLOAT }
feature { name: "dloss" type: INT }
feature { name: "dload" type: FLOAT }
feature { name: "dmean" type: INT }
feature { name: "dpkts" type: INT }
feature { name: "dur" type: INT }
feature { name: "dwin" type: INT }
feature { name: "dtcpb" type: INT }
feature { name: "is_ftp_login" type: INT }
feature { name: "is_sm_ips_ports" type: INT }
feature { name: "label" type: INT }
feature { name: "proto" type: BYTES }
feature { name: "rate" type: FLOAT }
feature { name: "response_body_len" type: INT }
feature { name: "sbytes" type: INT }
feature { name: "service" type: BYTES }
feature { name: "sinpkt" type: FLOAT }
feature { name: "sjit" type: FLOAT }
feature { name: "sloss" type: INT }
feature { name: "sload" type: FLOAT }
feature { name: "smean" type: INT }
feature { name: "spkts" type: INT }
feature { name: "state" type: BYTES }
feature { name: "stcpb" type: INT }
feature { name: "swin" type: INT }
feature { name: "synack" type: FLOAT }
feature { name: "tcprtt" type: FLOAT }
feature { name: "trans_depth" type: INT }
